### ISSUE TITLE
socket.io path is not modified

### ISSUE THREAD

**Issue by kumagi** [hackmdio/hackmd#137]
I set `"urlpath": "foo",` option in `config.json`.
All URLs seems to be started with `/foo`.

But `/socket.io/.*` path is not modified yet.
I think https://github.com/hackmdio/hackmd/blob/master/public/js/index.js#L1954 this line seems to be wrong.
`config.urlpath` is not reached here, so this line always results to become `path: '/socket.io/'`.

We should set this line can become `path: '/bar/socket.io/'` in case we set `urlpath: 'bar'`.

Thank you.

**Comment by jackycute** [comment]
Hi @kumagi

Because that settings (`urlpath` and `domain`) won't pass from server to client.
You have to set that again in here:
https://github.com/hackmdio/hackmd/blob/master/public/js/common.js#L3
I also mentioned that in README.md
https://github.com/hackmdio/hackmd/#client-settings-commonjs

And everything should be fine.

**Comment by kumagi** [comment]
@jackycute Oh, thank you!
I modified `common.js` and everything works well!
I apologize to you for a fuss over.
