### ISSUE TITLE
Can't paste at mobile browser

### ISSUE THREAD

**Issue by Superbil** [hackmdio/hackmd#151]
I change to edit mode, and it can't paste things at mobile.

iOS: 9.3.3

**Comment by jackycute** [comment]
Hi @Superbil 
The mobile input method vary on every OS (or even language or keyboard).
Since we're using CodeMirror, I would like to refer few issues from them.
https://github.com/codemirror/CodeMirror/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20ios

If you select a word or a single character first then the context menu will show up.
This might be the current workaround, thank you.
