### ISSUE TITLE
Few questions for production

### ISSUE THREAD

**Issue by amlwwalker** [hackmdio/hackmd#162]
Hi, 

This is so cool. I started a company recently, and I'm looking for an internal editor that is collarborative is markdown, and I can easily back up. Please can I ask a few questions:

1. Backing up:
I understand (please correct me) that _all_ information with regards to storing and editing documents is stored in the database. There is no file structure that would need backing up? I plan on running a cronjob that backs the database up to S3 every hour. 

2. Displaying files live
The use case I have is I have a wiki written where the docs are written in markdown. These are currently hosted on the filesystem. Where do I look in the database to pull the current version of a document out? I.e I want to use this to edit the content of the wiki, and when someone goes to a page on the wiki, they see the current static version (with all the CSS etc, that I want to apply). I can edit the wiki code to do a psql request, but I couldn't find the files in the DB

3. Is there anything you would suggest thinking about for using this in production behind a generic OAuth proxy?

4. I see the PDF feature is in Beta, is there a roadmap for this? I see it can't render things like the UML diagrams and flow charts, is there a specific CSS file for the rendering here? I presume telling the PDF renderer not to let diagrams etc cross pages is a CSS rule? : 
![image](https://cloud.githubusercontent.com/assets/2920180/17988126/2420301c-6b1c-11e6-87c1-eea3515cd905.png)

5. Is there any other options with regard to storing pictures except Imgur? Could I store them in S3 atall? I just don't want the pictures to be necessarily public

Thanks, and this is awesome

**Comment by jackycute** [comment]
Hi @amlwwalker, sorry for the late reply.
I would love to answer all your questions.

1. Yes, currently we store all our data in the DB, no other static files need to backup.

2. This might be difficult for now, the data we stored in the DB are compressed by LZString with Base64 encoding. And editing operations all are handled by the realtime server. But we could open HTTP API for that you need to pull current version and push a new version on.

3. Hmm, I don't get it. If you are thinking that you want to signin HackMD with your own OAuth service, please consider making a passport strategy since we use it (example: [facebook strategy](https://github.com/jaredhanson/passport-facebook)).

4. No clear roadmap for that, the suggest usage for export PDF will be print the page as PDF from your browser option. Because the PDF rendering from server will take a long time to parse/draw the diagram and apply CSS rules and that is not what our server affordable or user acceptable. The cross page image/diagram might able to control by CSS, but I haven't found out how. refer to #33 

5. Currently, No. But we are planning to support local upload (maybe S3 will also be supported), refer to #156

Thank you for loving us :heart: 
Feel free to ask more if you still have some.

**Comment by amlwwalker** [comment]
Thanks for your responses!

1. OK great, that makes it dead simple to backup
2. Right - it would be cool to be able to access the final version, perhaps in a read only format (and possible to make public. The beauty of this is the hackmd becomes the CMS for a wiki which would be oh so sweet. It also means the wiki can be anything the user likes, it doesn't have to be in anyway related to hackmd (which is my usecase exactly). With regard to an API what are we looking at in terms of complexity? There is already a "publish" button which is the read only button, so if a list of available files (in the DB) was available on an endpoint and an endpoint that returns a specific file (as the content) that would be pretty nice.
3. Yeah I might look into a passport strategy. A quick solution maybe to either turn off my auth and hand it to Hackmd, or have both
4. OK this isn't a big issue I don't think. I have markdown -> PDF working elsewhere, and as you say print to PDF would work to from the read only/publish page

5. S3 would be massive! Literally S3 is such cheap (private) storage. I would love to hear any progress on this

Thanks!

**Comment by jackycute** [comment]
2: Yeah, I was thinking about how to make HackMD as a knowledge base, but it's not a easy work to be a wiki. It's not possible to list all note from DB for now (no API for that). But there is a task #166 which about  user space, it that done and it might able to list all notes below to someone. The API maybe not very complex, it will be simple GET/POST HTTP request and server will handle the rest for you.

4: I found another way that how dillinger export PDF, print the publish page with phantomjs (headless), so there is another approach.

5: I agree with that. S3 is very good choice, definitely will do.

**Comment by amlwwalker** [comment]
s3 could do image storage too

**Comment by jackycute** [comment]
It's very nice to discuss with you!
Let's keep eye on image storage issue now.

reopen if you have other questions.

**Comment by jackycute** [comment]
also refer to #11
