### ISSUE TITLE
hackmd with matrix.org 

### ISSUE THREAD

**Issue by rdbl** [hackmdio/hackmd#175]
We would like use matrix registration and if the database will be distributed , it will be the best wiki of the world ^^ ( ok it's already the best ;) )

**Comment by ccoenen** [comment]
Could you go into a little more detail what the actual advantage of matrix.org would be? Federation, OK, but other than that? What is your intended use where you will need this?

**Comment by montitloup** [comment]
You could give the users the possibility to create wikis inside a chat client like Riot.im/app, that uses matrix.org as a federation et decentralized system.

**Comment by rdbl** [comment]
Matrix.org is very active and the community grow quickly . When we you riot , we have chat , video conference , audio conference , files transfert with room or peer to peer . lot of community need a good wiki and if we can create easily a wiki link on each room with sames authentication , it will be very useful .

**Comment by ccoenen** [comment]
Yes, and if we include Nextcloud, we have files, calendar, email, contacts. It has a very active community and grows quickly, too... but what is the point? I am not entirely convinced that integration really benefits anyone.

**Comment by almereyda** [comment]
The improvement would be that pages could live on multiple nodes, and could eventually be client-independent, as such federated. Also offline-resyncing scenarios become possible. The Matrix ecosystem could replace the storage and authentication layer.

**Comment by SISheogorath** [comment]
Since there is already a discussion ongoing on how this could improve, I would like to talk about the implementation side.

We currently use [sequelize](http://docs.sequelizejs.com/) as data layer and [passport](http://passportjs.org/) as authentication layer.

Both solutions work very well and are rock solid. Replacing them with a self-written solution which needs to be maintained is out of the scope of this project. So maybe you can suggest the needed libraries. Also, keep in mind that it adds a lot of latency to the whole setup and right now the entire system is not built for this level of resilience and distribution.

For Riot.im I can suggest using their "custom widget" feature to embed HackMD notes into the conversation. I already did that and it works well.

**Comment by SISheogorath** [comment]
For those who are interested in HackMD, just as note: I founded a #hackmd:matrix.org channel which is linked to the gitter channel.

If someone is interested in working on an Matrix.org integration (like logins) we can talk there 👋

**Comment by ccoenen** [comment]
To be honest, I don't think this worth the effort.
I have yet to see any advantage for HackMD of the proposed change. It also hasn't been active for over a year.

**Comment by frankgerhardt** [comment]
Agree

**Comment by SISheogorath** [comment]
Since there is not much interest right now, I'll close this issue and we will see later.

**Comment by frankgerhardt** [comment]
Understandable, that you close it. What's the roadmap for other features and what about community edition vs some other edition?

**Comment by SISheogorath** [comment]
Please check the community announcement: https://github.com/hackmdio/hackmd/issues/579

Actually there are no restrictions and (right now) no big plans on CE besides the PRs by the community.

In general if you search for a more interactive place reach out on [Gitter](https://gitter.im/hackmdio/hackmd) or [#hackmd:matrix.org](https://riot.im/app/#/room/#hackmd:matrix.org).

I think a roadmap would be a nice thing but I also don't want to do it on myself and push the project only into my direction. So some more conversation and interaction with the community would be nice to create some kind of roadmap. Feel free to participate :)
