### ISSUE TITLE
Multiplexing slides

### ISSUE THREAD

**Issue by wirew0rm** [hackmdio/hackmd#207]
Syncing the the currently active slide across devices would be pretty cool.

I see various usage scenarios:
- Distributed presentations for videoconferences
- Acessibility for people with impared vision and backrow seats
- Controling the slides on the beamer from mobile device or laptop on the speakerdesk

The clients would have to share the currently active slide with the server and the following clients would have to append some session identifier to the URL like `https://hackmd.io/p/slide-example#/?follow=<user/sessionID>` to get notified about slide transitions.

For the UI a "follow slides" button could be added to the menu, which allows to select a user. So by default slide mode would be launched as presentation master and everyone else can connect to it. Not sure if sharing the current slide with everyone with access to the note by default would be a problem tough.

This is already implemented in reveal.js and called [multiplexing](https://github.com/hakimel/reveal.js#multiplexing). The client part looks like it should have that is needed, the server part would have to be adapted or at least integrated.

Thanks for this really great project :)

**Comment by SISheogorath** [comment]
I thought a bit about this.

If someone wants to take some time and write it, here is where to go:

https://github.com/hakimel/reveal.js/blob/master/plugin/notes-server/index.js

I won't invest too much time on it, since the only place where I can imagine it being really useful are video conferences but there we are usually able to share screens which makes the feature, as cool as it is, obsolete.

But of course: PRs are welcome :)
