### ISSUE TITLE
Issue #270 seems not to be resolved?

### ISSUE THREAD

**Issue by Someniak** [hackmdio/hackmd#283]
It seems this issue has not yet been resolved in the docker image? Could it be the docker repo is not up to data? @tomwyckhuys

**Comment by SISheogorath** [comment]
@jackycute mentioned in #270 It's fixed in the new release. There was no new release so it's not fixed. You can run the unstable docker image using the latest tag. But it's not stable so it may breaks. (happened to me :/) So please try to use the released version. New release will coming soon. With updated Docker image.

**Comment by jackycute** [comment]
I will try to release in two days.
Be patient guys 😜

**Comment by jackycute** [comment]
0.4.6 released!
https://github.com/hackmdio/docker-hackmd
