### ISSUE TITLE
Feature request: Minimap

### ISSUE THREAD

**Issue by almereyda** [hackmdio/hackmd#310]
Atom is written in JavaScript, and has a Minimap. The good writing feeling in HackMD invites to also ask for such more convenient features here.

**Comment by jackycute** [comment]
We're using CodeMirror which not support minimap officially.
However I found once a PR have it.
https://github.com/codemirror/CodeMirror/pull/3358

Still not sure about to implement this or not.

**Comment by ccoenen** [comment]
This is just an opinion. I'm adding it, because of the `vote wanted` tag.

Personally, I use hackmd for documents foremost, where a visual representation is (in my opinion) less useful than in code. Code has highlighting (which plain text rarely has) and code also has a sort of rhythm to it.

For texts, the (very nice) folding table of contents is pretty much ideal. I'm not against the minimap, I just don't see myself using it a lot.

**Comment by SISheogorath** [comment]
FULLACK @ccoenen Another Problem that I see is that a minimap needs space. UI space.

The only place where I can think of this minimap is the fullscreen text editor in a landscaped direction. And for me there is no real benefit. If I write in the fullscreen edit mode I do it because I need space. And a minimap eats space. When I want to write and see where I am there is the splitted edit mode which is btw the mode I use most of the time. And yes there is also the preview mode which I use "never" until I click publish 😄 So If you want to add a minimap there I don't care. Everything else is a very difficult to handle in the ux/ui context.

**Comment by ccoenen** [comment]
I'll close this for now. Please feel free to reopen it, especially if more people come forward infavor of a minimap!
