### ISSUE TITLE
[Advise] Would hackMD have explorer or feed like blog?

### ISSUE THREAD

**Issue by fbukevin** [hackmdio/hackmd#331]
I think it would better to have `explorer`, `feed`, or `hot notes` whatever, function like most blogger have, because there are many good quality articles should be shared to public. :)

**Comment by SISheogorath** [comment]
<sub>Disclaimer personal opinion</sub>

HackMD is for taking notes. In my eyes notes are something very personal. If I want to share them I give someone a link to my note and the people can read and maybe modify them.

While a blog, like Ghost, is for sharing things with public, creating publication etc. So if I want to share an article with the world I write it in my blog, not in my notebook. And since in our modern world both is digital I can simply copy my article written in HackMD, paste it to Ghost and `*magic*` -> public article!

That is by the way my personal workflow for writing blog article. Taking notes, and write it down using HackMD and then copy it to my ghost backend, finish and publish it.

So for me having some kind of "feed" sounds against the whole idea of an application for taking notes.

And technically a feed in speech of an RSS feed etc. doesn't make much sense to me, as most of the notes are not very important and if you want to rank them the feed is changing to frequently to really keep it.

The `hot notes` functionally already exists. When you check your overview you see the recently changed notes at the top of the overview as long as you don't pin it. (Pinned notes are always at the top.)

In case you want to have statistics etc. HackMD already allows you to embed google analytics and Disqus to your notes, so it is easy to get all needed data.

**Comment by jackycute** [comment]
We would have a profile page which show all your notes and it will also present to people if your note permission allowed.
See more #166 and #314

**Comment by ccoenen** [comment]
Please let's not turn it into all things for all people. This is (in my opinion) for taking notes or collaborating on text-heavy content.

I would not see any problem in addressing your need in a plugin or seperate project. Starting with 0.5, the database is very easily accessible, so it wouldn't be too hard to write an automatic static export (something like Jekyll or nanoc) that creates plain HTML files for the world.

You certainly don't want to serve 5 MB of JavaScript to any regular Joe who just wants to read your blog.

**Comment by fbukevin** [comment]
Well, since I found HackMD has better markdown support for editing a note (or post),  it seems I misunderstand the idea of HackMD. I really appreciate that HackMD help me easily create notes.

😄

**Comment by jackycute** [comment]
Thanks @fbukevin 
Maybe we'll make this possible in the future.
