### ISSUE TITLE
sync scrolling to cursor position support

### ISSUE THREAD

**Issue by mistguy** [hackmdio/hackmd#365]
Currently, it seems sync scrolling is implemented to sync the first visible line in edit area. This makes it impossible to preview what I am current writing when, for example, the file contains a lot of pictures which take a lot of space in the preview pane. I think maybe the correct way to implement sync scrolling is to sync preview pane to cursor position.

**Comment by jackycute** [comment]
Hi @mistguy 
Thanks giving us suggestion.

But we've tried auto sync scrolling on cursor position, but it result very annoying because the preview pane will jump around when you do editing.
I think your issue is sometimes the edit pane height is smaller than preview pane and vice versa.
And that might cause your couldn't preview on the specific area you're editing.

There will two solution I could think of so far.
1. start sync scroll on cursor line when it reaching bottom of edit or preview pane.
2. double clicking on edit line or preview area to sync scroll to that line.

**Comment by mistguy** [comment]
Personally, I like the second idea. @jackycute

**Comment by jackycute** [comment]
@mistguy Me, too. Let's hand this on.

**Comment by ccoenen** [comment]
how about "syncing to cursor" only once the cursor is out of visible range of the right window? I have _no_ idea if this is possible.

This way, the current scrolling would be in place "most of the time". But for edge cases, the right window would auto-correct once the cursor leaves the top or the bottom.

**Comment by ccoenen** [comment]
I'd like to ask people who are having trouble with the scroll-syncing to report more how this could or should work. Personally, I rarely have problems (usually only with large box-ish things like images).

In case this is "good enough" I'd propose closing this issue in 2-3 weeks.
