### ISSUE TITLE
Wrong file paths in pretty.ejs

### ISSUE THREAD

**Issue by janniklorenz** [hackmdio/hackmd#42]
In `/public/views/pretty.ejs` almost all script paths are combined with the 'url' var to absolute paths

For example:
```
<link rel="stylesheet" href='<%- url %>/css/site.css'>
```

This makes some problems behind a proxy. 

Is there any reason, why absolute paths are needed here? The only one I could imagine would be to enable the possibility to embed the page on another webpage or in some download. 

And where ist this url taken form? It's not the `domain` or `getserverurl()`, which is defined in the config.

**Comment by jackycute** [comment]
This is for people who want to embed or download the published note.
To keep them view note properly in local network, I must do this.
I didn't specify the protocol in other file includes because those are in relative path.

And the url is generate in the way we render the page.
refer to:
https://github.com/hackmdio/hackmd/blob/master/lib/response.js#L194

May you describe the problem happened behind the proxy?

**Comment by janniklorenz** [comment]
The problem ist, that this url  var is `localhost:<port>`, which is no reachable from the internet.

What about using the result of `getserverurl()` for that var?

**Comment by jackycute** [comment]
Oh, ok. I know your problem.
I will try to fix that.

**Comment by jackycute** [comment]
Try to fixed this in 75ae505a1544d8999e6705aad7ed96ff5a6eb0e5
Please test.

**Comment by janniklorenz** [comment]
It works. Thanks.
