### ISSUE TITLE
Allow *free url* mode like etherpad

### ISSUE THREAD

**Issue by amigrave** [hackmdio/hackmd#44]
I really like hackmd, I have a dedicated local instance for my personal notes and use it everyday for my projects.

In this context I'd like to be able to choose my URLs instead of having them generated trough `uuid`.
This would allow a better organisation of notes and easy linking between them.

So basically, entering a non existing url eg:  `/projects/foobar` will automatically create a note at this url.

This coupled to a kind of `global userspace` option, hackmd could even be used as a wiki or an internal reference web space.

I understand this feature is incompatible with the default usage of hackmd which has a per-user context separated design, this is why I propose to allow this new behavior as an opt-in configuration option.

If you agree with the principle I'll work on that and propose a pull request some day.

**Comment by jackycute** [comment]
Wow, Thank you!
I think this is the biggest praise to this project (and me).

Yes, you're totally right.
When it comes more notes, it will need a good method to rearrange them.
And customizable url seems to be the best choice to remind and store at same time.

Also, I was planned and would like to build a collection or folder mechanism.
But I'm busy on other things in this time, and that will be great if you want to help.
You can also see whole feedback and suggestions here:
https://hackmd.io/EYdmEYENwFgZgLQAYngGYJgJgCbAZAKygKxYw4CmMIkaSAnEAAA=

To build this feature I would also recommend to have a dropdown to let user do what they want.
Like jsfiddle dose:
![image](https://cloud.githubusercontent.com/assets/2639151/11427700/a8637a74-942a-11e5-92cc-9c81c8661b83.png)

This idea is not conflict with the experience which hackmd what to give.
It's mainly want to provide one-site, for personal or groups using, collaborable doc, blog, note, slides at a time.
Sounds very greedy, but that's what I want to do: push markdown and plain text writing to a even upper level.

Thanks again!

**Comment by viderizer** [comment]
I really like this suggestion and would like to see it implemented too.

**Comment by jackycute** [comment]
Hi @eppfel !
I plan to make user space before user-defined URLs because these two issues are related.
The note url will become like `https://xxx.xx/@username/custom_url`, so the user space will be needed.

And about the jsfiddle did is refer to above image, when user push publish will popup a dropdown dialog which contains possible sharing options and reminder of some metadata.

Hope this answer your questions.

**Comment by eppfel** [comment]
Awesome project btw. Hopefully I find some time to contribute.

**Comment by esbite** [comment]
This is the only feature missing for our company to be able to ditch our old ether pad installation and start using HackMd instead! Awesome project!

For us the URL's would really need to be global though, not user spaced. This is for two use cases, both for an internal wiki and for our project stories where we create shared pads with the story number in the URL.

Is there anything we can do to help out developing this feature? :)

**Comment by jackycute** [comment]
OK, I will support doing global space note first.
Like visit `/free-url` will create a note with that alias.

**Comment by jackycute** [comment]
It pretty hard to support multiple level on free url.
Is it acceptable to use like `/projects-foobar` for now?
@amigrave and other participants?

**Comment by amigrave** [comment]
Yes of course ! Etherpad does not handle multiple levels urls either when creating a note.
I was just illustrating the use case, but dashes and/or low-dashes are as good as slashes.

Functionally, those urls

    /projects      # list of projects
    /projects/foo  # project foo 
    /projects/bar  # project bar

are the same as those

    /projects      # list of projects
    /projects-foo  # project foo 
    /projects-bar  # project bar

I think it's even better for future features url mapping because if you consider that root ( / ) and multiple level urls ( /*(/*)+ ) are not valid "free-urls", then you know that you still can add more features without url namespace clashes (eg: adding an api will not interfere with free-urls):

    /api/notes/list
    /api/notes/create
    /api/user/create
    ...

I'm sorry I can't help on hackmd but I accepted a side project that eats up all my free time.

**Comment by esbite** [comment]
@jackycute Oh yes we would host our own instance locally anyway so that would be awesome!

**Comment by jackycute** [comment]
Supported in 5bb3de2675967eb2f6ea295e7c3e969769ed2a70
If anyone want a further implementation, please open another issue.

**Comment by grexe** [comment]
Can only join the praise for HackMD, my favorite collab tool currently.
Following this issue and seeing the patch, I'd really love to see a more Wiki-style approach to this (as an addition) - that is, taking the name automatically from the title, what do you think @jackycute ?

**Comment by jackycute** [comment]
Thanks for your kind words @grexe !

But I don't think take the name directly from title is a good idea in here.
Because the freeurl is now root level naming, which means it will need to add hash to solve the naming conflicts (just like hackpad or medium did) (I don't like blend random string to static strings).
And what if you change the title by accident or just in typing? It won't able to access via the old urls.

So we might let user "choose" their permalink to the note, which relatively static to the user space  like: `https://hackmd.io/@jackycute/that-is-how-we-do-it`.

What do you say?

**Comment by grexe** [comment]
I see the issue, true, just searching for a way to mimic the common
Wiki-behavior...
What about prompting the user for a page name that is used for the URL
right when creating the note?
Is this what you proposed?
Then I'd be all for it, seems to be a good compromise.

**Comment by jackycute** [comment]
@grexe Something like that, yes.
But I think we could postpone the page naming after creating the note.
I would prefer add the page name option in the "publish" process.
Because it's a bit pain if you got interrupted when you're full ready to type.

**Comment by jackycute** [comment]
Wait, I think I get you wrong.
Let's make it clear, why do you what to taking the name automatically from the title?
And what do Wiki-style approach benefits?
Could you explain you need more detail? @grexe 
I would like to figure out a way that suits us the best.

**Comment by grexe** [comment]
@jackycute you're right about not breaking the flow, I'd be fine with specifying the name on publish.

You got me right, forget about automatically taking the name from the title, you convinced me otherwise:) Would be nice to *suggest* the URL name from the title and display that as default in the naming dialog, maybe.

**Comment by apoikola** [comment]
"This won't available in official service"

Any chance of deploying it there as well? I believe that the official version is the way for most to get familiar with this great project and the free-url feature is really important.

It is already "used" at least in the documentation pages like: https://hackmd.io/features

I was lucky to end up here (after random googling) so that I know that this feature even exists in self-deployed versions. If not, I might have mis-judged that HackMD is not fulfilling our needs.

Anyhow, thanks for the project!

**Comment by almereyda** [comment]
@apoikola You can try out free URL mode on a public instance documented at https://discuss.okfn.org/t/shutting-down-pad-okfn-org/4893/3?u=almereyda

**Comment by rastapopougros** [comment]
Hello, I come back on this issue, cause we have a 1.2.1 instance (not so old then), and in config.json, in the "production" section, we have `"allowFreeURL": true`.

And… nothing, when we access ourinstance/anystring, we always have a 404 error.

How to trace the problem?

**Comment by SISheogorath** [comment]
@rastapopougros please feel free to join our [communtiy channel](https://riot.im/app/#/room/#codimd:matrix.org) for debugging. Otherwise I would suggest to open an own issue, since this is a feature request, while yours, given that it's not a misconfiguration, is a bug.

**Comment by rastapopougros** [comment]
(I tried, dozen of times, to register to Riot, "email was sent to x@x" but never received. And the address works well, and nothing in spam.)

**Comment by ccoenen** [comment]
Matrix is just a service we use, so we sadly don't have any control the signup problem.

If your free url problem still persists now that we've released 1.3, we can certainly also discuss it in one of these issues.

**Comment by Depau** [comment]
I can confirm the issue exists on my instance.

**Comment by mitchellurgero** [comment]
I am also seeing this issue on my instance as well, version 1.3

**Comment by Depau** [comment]
Issue has been fixed in the community fork, https://github.com/codimd/server
