### ISSUE TITLE
Increase document length

### ISSUE THREAD

**Issue by Destroyer** [hackmdio/hackmd#440]
Hi, thank you for this amazing tool. I am using it to write my school notes. Unfortunately I hit the cap of 100 000 characters. I'd like to have all lectures from one subject in one note.  Is there a possibility you might increase the cap to 150 000+? Or do I have to selfhost and configure it myself?

**Comment by jackycute** [comment]
Hi @Destroyer 
You might need to self host a instance for increasing the document length.
The document length actually affect the system compute performance, so that's why we keep it in 100,000.

BTW, the official service (hackmd.io) have added book mode recently, which might be useful for you.
https://hackmd.io/book-example

**Comment by Destroyer** [comment]
I guess I'll selhost then. The book is an interesting concept and I might use it in the future for something else, but it breaks search functionality which is crucial for me.

**Comment by jackycute** [comment]
No problem.

**Comment by correctmeifimwrong33** [comment]
Solution: in `/home/hackmd/app/lib/config/default.js` change `documentMaxLength` from 100k to e.g. 500k

If using docker, note you need to change either only `overlay2/<hash>/merged/home/hackmd/.../default.js` or both that and `overlay2/<anotherhash>/diff/home/hackmd/.../default.js`, I'm not sure (I tried both but it only worked after changing the `merged` one). Then find the container ID in `docker ps`, also some sort of hash, and run `docker restart <containerhash>`

I wanted to paste error output into codi. After raising the limit, codi and the browser handle it perfectly fine, so I guess the limit is there for more complex documents (imo: let the user find out by themselves when performance starts to degrade and make their own choices instead of arbitrary hard limits)
