### ISSUE TITLE
Runaway memory when document left open in edit mode

### ISSUE THREAD

**Issue by conspacer** [hackmdio/hackmd#441]
This is only from using hosted hackmd on the following:

- firefox 53.0
- Chrome 58.0.3029.81
- Windows 10 Insider

Leaving a document open in edit mode for a few hours and the browser eats up memory. Last night I even got the Windows low memory error (1 have 16Gb). This is with no other tabs or windows open.

I will test with a few more browsers and on a Linux machine (on the same hackmd host) to see if the issue persists.

**Comment by a60814billy** [comment]
Hi @conspacer 
I cannot reproduce your problem, my environment is 

* windows 10 (64bits) build 1607 (14393.1066)
* Chrome 58.0.03029.81 

I open my self-hosted HackMD (0.5.1), and open in edit mode.
After 24 hours, the tab uses about 300MB memory.

**Comment by SISheogorath** [comment]
I also tried to reproduce it yesterday and today with multiple browsers on Linux. Nothing found. Tested with chromium's memory timeline and checked for growing object counts etc. But no success.

Tested http://hackmd.io and my self-hosted instance. Always used the "Feature"-Page to test.

If you can provide a link to the document where you noticed it and also check that it with a new Firefox or Chrome profile it would help to identify the problem. My current guess is that it's not a HackMD problem (maybe caused by another page open during the night, too?)

**Comment by conspacer** [comment]
Thanks @a60814billy  and @SISheogorath for the input. 
It must be my server (its just a sloppy staging), I will do a clean re-install and load the same documents and test again.
(marking closed, if anything will reopen with documented results)

**Comment by Marwe** [comment]
I experience the same issue on chromium on Linux since a while (maybe since I use hackmd).
chromiums task manager tells me, that the general memory consumption increases steadily, the tab related memory increases, but on a much smaller level (~1%). Consumption is about 1-2 MB/sec, so I have about 4 hrs. until I run out of 16G memory ;)

Additional consumption stops by closing the hackmd tab, but the memory consumed stays consumed until restart/kill of chromium.

If there is a way to debug futher, what the memory is used for, I would like to know.

**Comment by SISheogorath** [comment]
Hi @Marwe,
could you put this in a new issue, as this here described problemis more than a year old and there were a lot of changes.

---

Apart from that, can you try to reproduce this on our latest stable branch instance: https://hackmd-ce.herokuapp.com
