### ISSUE TITLE
custom css and themes in slide mode

### ISSUE THREAD

**Issue by zeigerpuppy** [hackmdio/hackmd#467]
Is there a way to link to a custom CSS file for slides?

I'm also not sure how to change the slide theme

This should be possible by inserting a custom CSS link in the header but I can;t find how to enable this feature.

**Comment by zeigerpuppy** [comment]
looks like this can be hacked by adding a style link in the body of the HTML.

eg:
```
<style type="text/css"> @import url("https://my.tld/uploadify.css"); </style>
```

**Comment by jackycute** [comment]
Hi @zeigerpuppy 
For changing the slide mode theme, please refer to #437 

You could use `<style>` tag to define your styles.
But it's not safe to load external CSS or `@import` in CSS.
We'll filter it that soon.

**Comment by zeigerpuppy** [comment]
I can see how this is a pretty major security issue.

It would be good to have a relatively easy method of editing themes.  I tend to do quite a bit of CSS customisation when making reveal.js slides (mostly for fitting images and defining some custom elements).  Perhaps we could link to a CSS file stored in another hackmd note that is automatically created when presentation mode is used?

So going to slide mode would create something like:
```
https://hackmd.server.net/GwRgTALGDsBCChkkBBDMTWYFYREDoD4CwQIBTWcIA#CSS
```

**Comment by jackycute** [comment]
`@import` in style tag will been removed after d96385eafdc8e9c408088a3f95a60c9a0193ef67

**Comment by SISheogorath** [comment]
@zeigerpuppy Do you need really additional capabilities? Inline styling is fine and you can now define themes for your presentations.

Can you explain what additional styling you need? Or what benefit external style sources provide?

**Comment by dbrgn** [comment]
I'd like to customize fonts with custom CSS. Inline <style> would be fine.

It seems to work for the regular page, but not for the slides.

**Comment by zeigerpuppy** [comment]
I'm going to try a workaround for this by mounting the theme folder as a bind mount so that I can edit custom themes more easily

docker compose V2
```
volumes:
      - /hackmd/uploads:/hackmd/public/uploads
      - //hackmd/uploads:/hackmd/themes:/hackmd/public/build/reveal.js/css/theme
```

**Comment by SISheogorath** [comment]
I would recommend to contribute these theme changes upstream to reveal.js instead of opening up another problem we need to fix. I agree that this way works and is fine for people who are really into CSS but I also think these people are capable of writing a file like that.

Given the case we make it within the next few month to get an admin panel and more Backend and management parts in general, we can for sure add a field to add custom styles. For now, if you like to document it into the wiki or the docs directory, I think it's enough for most users.

So closing this for now.
