### ISSUE TITLE
Convert Domains to URL with SSL if available

### ISSUE THREAD

**Issue by davidak** [hackmdio/hackmd#534]
Domains in the text get converted to URLs.

Example:

Golem.de -> http://golem.de/

It should use **https** if available. Otherwise it's a security risk for readers.

**Comment by SISheogorath** [comment]
We can't blindly convert HTTP to HTTPS. This is not the task of the editor. If want to use https, type it.

To prevent security risks like that, HSTS preloaded exists. If the page doesn't provide it, we can't help.

If we want to check this it's way more complicated because you have to check the following things: 1. 

1. Is the page available as HTTPS?
2. Is the content of the page on HTTP the same as HTTPS?
3. Is the TLS cert trusted? How do we know?
4. Does the page show the same content to us, as it does to the user?

We don't want to check these things on the client-side for security reasons. But we can't know the client's certificate store on the server-side. So we can't do anything about it.

It's technically non-sense to do such a rewrite.

**Comment by davidak** [comment]
Alright, thanks for the explanation.
