### ISSUE TITLE
How to import .md file or other hackMD document into my hackMD

### ISSUE THREAD

**Issue by StacieR** [hackmdio/hackmd#537]
Hi ,
I have some other hackMD files on the server and .md files in my computer, now we built another enviroment with docker which could login, but I lost when I want to import my own files, I clicked all the icons and buttons on the first page and the new md page, seems could not import, could you please help me?

**Comment by SISheogorath** [comment]
Hi,

right now, we don't provide an export or import function for multiple HackMD documents at once. If you migrate the servers, you should migrate your database, too.

Otherwise, you can use the Markdown export for every single document, but that's pretty hard.

If you want to write an export/import function: Pull Requests are welcome :)

**Comment by ccoenen** [comment]
There's a bulk exporter for all stored documents in the Git-export-pull request: https://github.com/hackmdio/hackmd/pull/303 maybe that could be a starting point for your project. There is, however, no automatic import. So you might be stuck with Copy&Paste for import.
