### ISSUE TITLE
Anchors not changing current URL when document viewed as a folder item

### ISSUE THREAD

**Issue by KrzysztofMadejski** [hackmdio/hackmd#546]
I've landed on Civic Tech Fest unconference notes on http://beta.hackfoldr.org/civictechfest/https%253A%252F%252Fhackmd.io%252FKwUwhgZgzAbAxsAtAIwBwAYKICxmAdhQEYQQd1URsYRUAmEATiiA and clicking links on documents section doesn't update URL.

 I have to copy it manually from the TableOfContents list or from the section headers. Then it works. I see that the links have different format: https://hackmd.io/KwUwhgZgzAbAxsAtAIwBwAYKICxmAdhQEYQQd1URsYRUAmEATiiA#findings-of-the-taiwan-open-government-report-po-yu-tseng-and-mg-lee-open-culture-foundation-taiwan

Maybe the first link should redirect to the second?

**Comment by SISheogorath** [comment]
I think this error is based on the fact, that http://beta.hackfoldr.org/civictechfest/https%253A%252F%252Fhackmd.io%252FKwUwhgZgzAbAxsAtAIwBwAYKICxmAdhQEYQQd1URsYRUAmEATiiA is only a wrapper that provides an iframe for https://hackmd.io/KwUwhgZgzAbAxsAtAIwBwAYKICxmAdhQEYQQd1URsYRUAmEATiiA#findings-of-the-taiwan-open-government-report-po-yu-tseng-and-mg-lee-open-culture-foundation-taiwan

Since iframes don't have access to the URL of the side they are embed on, there is no way for HackMD to update it.

But maybe I got your problem wrong and you mean something different

**Comment by KrzysztofMadejski** [comment]
Yes, I believe you got it right. So anchors are not working when viewing the document in the catalogue view.

It really impacts sharing.

**Comment by SISheogorath** [comment]
To me it looks less like a HackMD problem than more like a [hackfolder](https://github.com/hackfoldr/hackfoldr-2.0) problem in this case. Not sure how that can be handles by them, but since it's an iframe, we can't do anything outside.

My advice would be to visit [hackmd.io](https://hackmd.io) directly.

**Comment by KrzysztofMadejski** [comment]
That seems to be HackMD repo so I guess its problems belong here? 

Could you tag/ping someone that have authority to resolve it? I don't know hackmd/hackfolder relations..

**Comment by KrzysztofMadejski** [comment]
If I got the repo wrong I'd be grateful for a hint where should I post this issue.

**Comment by SISheogorath** [comment]
It looks like @poga is one of the Hackfoldr people. Maybe he can clear the situation up.

**Comment by KrzysztofMadejski** [comment]
I shouldn't report issues at 3pm. I've read it again and it's totally a hackfolder problem. Closing and reposting there.
