### ISSUE TITLE
Create new document in a catalog

### ISSUE THREAD

**Issue by KrzysztofMadejski** [hackmdio/hackmd#547]
I've tried to collaborate on notes from Civic Tech Fest, but I couldn't find as simple feature as adding a new document in the catalogue/folder structure. TTcat came to the rescue. Editing the spreadsheet is the acky way, but it should be a way more straightforward.

It could be an empty row with a plus sign at the end (or the beginning) of catalogue documents.

**Comment by SISheogorath** [comment]
I guess as in #546  it's also here more a [hackfolder](https://github.com/hackfoldr/hackfoldr-2.0)  -> [hackfoldr.org](https://hackfoldr.org) problem than a HackMD problem.

Because right now, I'm not sure what catalog you are talking about when it comes to HackMD.

When it's https://hackmd.io it's related to HackMD, when it's on https://hackfoldr.org or https://beta.hackfoldr.org, it's related to https://github.com/hackfoldr/hackfoldr-2.0

If you are not sure, feel free to provide a screenshot, to let us clear up the situation.

**Comment by KrzysztofMadejski** [comment]
Right, I didn't provide enough context.  Use case:
1. I go to http://beta.hackfoldr.org/civictechfest/https%253A%252F%252Fhackmd.io%252FKwUwhgZgzAbAxsAtAIwBwAYKICxmAdhQEYQQd1URsYRUAmEATiiA
2. I want to create a new document under `Unconference` folder; I expand it..
3. ... I don't know how to do it [now I know, but it's really unintuitive]

Thank you @SISheogorath for support.

**Comment by SISheogorath** [comment]
Yes, that's also something hackfoldr has to take care of, since it's not part of HackMD.

Sorry that we can't address this.

**Comment by KrzysztofMadejski** [comment]
Hackfoldr related totally, moivng there!
