### ISSUE TITLE
feasibility of use hackmd as module?

### ISSUE THREAD

**Issue by laysdra7265** [hackmdio/hackmd#555]
只是一個構想，因為我想要尋找一個wiki式&任務管理系統，找來找去不是不合適就是編輯器很爛，hackmd的編輯器在共同編輯上做的很棒，但是和我需要的還差了點，我在想如果可以將hackmd的編輯器&文件系統稍作修改後作為一個模塊放進自己寫的一個任務&wiki知識管理平台的可行性，你們覺得呢

**Comment by SISheogorath** [comment]
你说英语请吗？我们手一点汉语。我们可以说一点汉语。

**Comment by laysdra7265** [comment]
Oh,OK,my bad.
I need a Wiki knowledge management & task management service to collaborate with friends.But all the service I can found not satisfied my requirement or my friend has some environmental restrictions to use those services or the document editor is too hard to use(editor function is too simple).I thought that hackmd is really awesome ,but still not complete meet my requirement.So I an idea comes up that if I can use hackmd as a editor&document module with other module like task management .Is this idea feasible?

**Comment by SISheogorath** [comment]
Right now you can use HackMD in another place by embedding it.  using an iframe. It's not a perfect solution but the easiest possible because we load a lot of additional scripts and styles.

In general when you want to use HackMD as something like a wiki, maybe http://hackfoldr.org is something you want to test.

**Comment by laysdra7265** [comment]
thx,I'll take a look.

**Comment by ccoenen** [comment]
I'll close this for now. If you have further questions, don't hesitate to ask!

If you have any particular things you need added (or even which you want to add yourself!) we'd welcome suggestions and pull requests!
