### ISSUE TITLE
Title unchanged when posted on social media

### ISSUE THREAD

**Issue by olaolaola0** [hackmdio/hackmd#557]
Just find a small issue.

When I post the published link (https://hackmd.io/s/blablabla, for example) of a note onto Facebook once the note is published, the title on FB remains unchanged no matter how I modify the title in the original note or simply re-post the link.

If I use the view-mode link (https://hackmd.io/fjcwejfeoje==?view, for example) of the same note, the title on FB will change accordingly.

**Comment by SISheogorath** [comment]
I just tested. So the code for the page changes, which is a good sign.

My guess: Facebook caches the title and the preview for a link. How to verify? Add a random number like in this example:

https://hackmd.io/s/blablabla?t=20171002

This should refresh the title since the URL is no longer cacheable this way. And in general the information should refresh over time. The parameter itself has no meaning to HackMD, but prevents Facebook from caching it.

Hope this solves the issue.

**Comment by jackycute** [comment]
Please clean your url cache in facebook debugger https://developers.facebook.com/tools/debug/

**Comment by ccoenen** [comment]
I doubt this is under our control.

**Comment by SISheogorath** [comment]
Closing this issue by inactivity. Probably out of the scope of this repository.

Feel free to reopen if the mentioned workarounds don't work.
