### ISSUE TITLE
html comments ruin <ol>

### ISSUE THREAD

**Issue by einarmagnus** [hackmdio/hackmd#587]
I am writing a math test using this, it is brilliant to be able to use LaTeX math instead of equation editor, and markdown instead of LaTeX text. Great, tanks!

Only problem for me is that I wish to insert the correct answers in-between problems as html comments but that breaks the automatic numbering. 

```
1. Förekla följande uttryck så långt som möjligt:

    a) $\frac{6xy^5}{2x^3y^2}$
    
    b) $\frac{2x\ +\ x^2}{2x}$
    
    c) $\frac{x^2\ -\ 1}{x\ +\ 1}$
<!--facit 
a) $\frac{3y^3}{x^2}$
b) $\frac{2+x}{2}$
c) $x-1$
-->

1. Givet två polynom $p_1 = 3x^2-2x+3$ och $p_2 = 2x^2+2x+7$,  
räkna ut $p_1 - p_2$ och faktorisera resultatet.
<!-- facit
$p_1 - p_2 = x^2-4 = (x+2)(2-2)$
-->

1. Faktorisera följande polynom:

    a) $4y^2-6y$
    
    b) $4x^2-16$
    
    c) $x^2-4x+4$ 

<!-- facit  
$2y(y-3)$
$(2x+4)(2x-4)$
$(x-2)^2$
-->

```

Without the html comments I get automatic numbering of problems, but with it I have to keep track of order myself. Perhaps this is impossible because inserted html could be anything I guess, but if you could ignore comments so that document with and without comments had the same semantics, that would be great!

Thank you!

**Comment by SISheogorath** [comment]
This is currently by design.

The markdown parser we use called [markdown-it](https://github.com/markdown-it/markdown-it) respects comments and renders them into the output HTML.

Since it has a block and an inline parser which run one after another it splits up every list with a comment block. Means for the parser it's not the same list. So everything that is built like `<list><something><list>` will not continue the list since a comment works for this parser like any other content block (e.g. a paragraph, a table, …).

There is an extension called [markdown-it-inline-comments](https://www.npmjs.com/package/markdown-it-inline-comments) which may resolve this issue. The possible problem I see is that it breaks other functionalities which may use comments, like the slide mode.

Also, it's possible that some people want their HTML comment kept in the document and since it's the current behavior and useful, for sure, I wouldn't like to break this functionality without asking the community.

So it's up to a discussion of the community if we want this feature or not.

Also, someone should build a PoC if it's wanted to prove that it works or not. PRs are welcome! ❤️

**Comment by einarmagnus** [comment]
It's not important.

I figured out I can write 
```
<style>
#doc pre {
    display: none;
}
</style>

1. Förekla följande uttryck så långt som möjligt:

    a) $\frac{6xy^5}{2x^3y^2}$
     
    b) $\frac{2x\ +\ x^2}{2x}$
    
    c) $\frac{x^2\ -\ 1}{x\ +\ 1}$

   ```facit 
    a) $\frac{3y^3}{x^2}$ 
    b) $\frac{2+x}{2}$
    c) $x-1$
    ```

1. Givet två polynom $p_1 = 3x^2-2x+3$ och $p_2 = 2x^2+2x+7$,  
räkna ut $p_1 - p_2$ och faktorisera resultatet.

    ```facit
    $p_1 - p_2 = x^2-4 = (x+2)(2-2)$
    ```

1. Faktorisera följande polynom:

    a) $4y^2-6y$
    
    b) $4x^2-16$
    
    c) $x^2-4x+4$ 

    ```facit
    $2y(y-3)$
    $(2x+4)(2x-4)$
    $(x-2)^2$
    ```
```
