### ISSUE TITLE
Recognize svg on drag and drop

### ISSUE THREAD

**Issue by akhmerov** [hackmdio/hackmd#637]
Observed on latest image (99ecdcc40fa9) using the default docker-compose, host OS Ubuntu 16.04.

To reproduce drag and drop an svg image into a note. Observe that the svg source is inserted. Expected result: svg is uploaded (just like any other image).

Unfortunately there is at least one subtlety here—I don't think if imgur is set up as an image hosting service, it will allow for svg images.

**Comment by SISheogorath** [comment]
Yes, Imgur doesn't [support SVG](https://help.imgur.com/hc/en-us/articles/115000083326-What-files-can-I-upload-What-is-the-size-limit-). But HackMD does since you can insert HTML directly.

But of course, that's not perfect. We can maybe allow upload SVG and more formats by making this configurable:

https://github.com/hackmdio/hackmd/blob/e2d821a30922551395e33a39ed79d28b50c383b9/public/vendor/inlineAttachment/inline-attachment.js#L144-L149

**Comment by akhmerov** [comment]
Ah, but on the other hand consider this: right now uploading svg won't work at all (and if an svg is large it will crash the browser). Therefore adding svg as an allowed attachment type would make it work for all installations except for those using imgur. From that perspective enabling svg as an allowed attachment type is a strict improvement.
