### ISSUE TITLE
HackMD doesn't allow inline math syntax that has space character right after/before the opening/closing dollar sign

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [hackmdio/hackmd#669]
For example, `$ \frac{3}{4} $` should also be interpreted as `$\frac{3}{4}$`.  Is there any reason not so support this behavior?

**Comment by jackycute** [comment]
Hi @Lin-Buo-Ren 
But that's part of the design of the inline math syntax.
You shouldn't put space around the opening/closing dollar sign.

refer to our package: https://github.com/classeur/markdown-it-mathjax

**Comment by Lin-Buo-Ren** [comment]
Thanks for the pointers!  I never notice the syntax until now 🤦‍♂️

**Comment by cben** [comment]
I see that CodiMD (and HackMD) also support `\\(inline\\)` and `\\[display\\]` syntaxes.  But these are not documented in https://demo.codimd.org/features?both#MathJax — do you consider them "official"?

Only single-dollar syntax has this limitation about spaces (to reduce false-positives for people using dollar sign without intention or even awareness of math syntax).  `\\( a^2 \\)4`, `\\[ a^2 \\]4`, and `$$ a^2 $$` all parse as math alright; newlines instead of spaces work too.

**Comment by SISheogorath** [comment]
@cben I would really welcome a Pull Request including an example to [our docs page](https://github.com/hackmdio/codimd/blob/master/public/docs/features.md) :)

This would make it official :+1: (at least for CodiMD)

**Comment by Lin-Buo-Ren** [comment]
I would really like to make it configurable via YAML though...

and \escape all the regular usage of the dollar sign.
