### ISSUE TITLE
Weird parsing

### ISSUE THREAD

**Issue by Nowaker** [hackmdio/hackmd#82]
`Today $20 (Tomorrow $50)` renders as:

![today](https://cloud.githubusercontent.com/assets/611746/12502512/44bcabb2-c08f-11e5-861d-3acf124569b0.png)

**Comment by jackycute** [comment]
This is because the Mathjax support and LaTex syntax.

```
The *Gamma function* satisfying $\Gamma(n) = (n-1)!\quad\forall n\in\mathbb N$ is via the Euler integral
```
will be
![default](https://cloud.githubusercontent.com/assets/2639151/12502554/bb76a974-c08f-11e5-85e8-1125ed79d86f.png)

```
$$
x = {-b \pm \sqrt{b^2-4ac} \over 2a}.
$$
```
will be
<img width="198" alt="2016-01-21 10 37 40" src="https://cloud.githubusercontent.com/assets/2639151/12502556/c0c37646-c08f-11e5-8d77-0cb805697ad0.png">

> More information about **LaTeX** mathematical expressions [here](http://meta.math.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference).

**Comment by jackycute** [comment]
You might need do it like this Today `$20` (Tomorrow `$50`)
```
Today `$20` (Tomorrow `$50`)
```

**Comment by jackycute** [comment]
OK I found I need to implement the escape syntax for it.
Thanks a lot!

http://mathjax.readthedocs.org/en/latest/tex.html#tex-and-latex-math-delimiters

**Comment by Nowaker** [comment]
Why not disable TeX by default and let only in ```latex block?

**Comment by jackycute** [comment]
Good question.
Because that's an feature from Mathjax, which HackMD is using right now.
See more at: http://mathjax.readthedocs.org/en/latest/misc/mathjax-in-use.html
Also lots people already known this syntax and use it a lot, it's convention I think.

But I would like to provide YAML meta that can disable this.

**Comment by jackycute** [comment]
Supported in 229740e478fc808a6e4fdece62c5158ead5f66e4
use following YAML meta to turn off maxthjax:

```
---
mathjax: false
---
```

For more information, please visit: https://hackmd.io/s/EyxWwA7Kvx

**Comment by jackycute** [comment]
Very good news!
After 1da0b87714e725dcd540f389b118c581fd93ccb7
Now if you have number surrounding with `$`, mathjax won't be applied.
That's mean this case won't happen anymore!
